version: "3.9"
services:
    app:
        build:
            context: ..
            dockerfile: app/Dockerfile
        container_name: app
        ports:
            - "0.0.0.0:5005:5005"
        entrypoint: ./entrypoint.sh
        environment:
            - POSTGRES_USERNAME=${POSTGRES_USERNAME}
            - POSTGER_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - SECRET_KEY=${SECRET_KEY}
        hostname: subscription-app
        depends_on:
            db:
                condition: service_healthy

    db:
        restart: always
        image: postgres:14.3-alpine3.16
        container_name: ${POSTGRES_HOST}
        environment:
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT_INTERNAL=${POSTGRES_PORT_INTERNAL}
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT_INTERNAL}"
        hostname: ${POSTGRES_HOST}
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 5s
            timeout: 30s
            retries: 6



